### ISSUE TITLE
Good luck guys!!!

### ISSUE THREAD

**Issue by lukabratos** [themondobot/mondobot-backend#1]
![](http://media4.giphy.com/media/609o8uNjasiJO/giphy.gif)

**Comment by Dan2552** [comment]
thanks 👍

**Comment by mcamara** [comment]
hvala!

**Comment by Dan2552** [comment]
![img_3555](https://cloud.githubusercontent.com/assets/1478221/14582498/79e400a8-03fe-11e6-95f8-af9007009713.PNG)
